# Generated by Django 5.0.7 on 2024-11-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0011_task_delete_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completedScrapping',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='completedSentimentAnalysis',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
