# Generated by Django 5.0.7 on 2024-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0012_alter_task_completedscrapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('scrapping_status', models.CharField(default='Pending', max_length=50)),
                ('sentiment_status', models.CharField(default='Pending', max_length=50)),
                ('scrapping_completed', models.BooleanField(default=False)),
                ('sentiment_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user', 'session_id')},
            },
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
