# Generated by Django 5.0.7 on 2025-01-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_taskstatus_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AlterField(
            model_name='sentimentresult',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platforms.review'),
        ),
    ]
